name: Lint and Type Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-type-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  
          pip install -r requirements-other.txt
          mkdir .mypy_cache
          mypy --install-types

      - name: Run Ruff
        run: |
          ruff check . 

      - name: Run Mypy
        run: |
          mypy --config-file "pyproject.toml"
